name: Build and Compact Debian XFS Image

on:
  push:
    branches:
      - main
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends qemu-utils libguestfs-tools xfsprogs

      - name: Download Debian Cloud Image
        run: |
          wget -O original.qcow2 https://cdimage.debian.org/images/cloud/bookworm/latest/debian-12-nocloud-amd64.qcow2

      - name: Convert Filesystem to XFS and Resize
        env:
          LIBGUESTFS_BACKEND: direct
        run: |
          qemu-img create -f qcow2 -o compression_type=zlib debian-12-xfs-uncompacted.qcow2 10G
          chmod a+r debian-12-xfs-uncompacted.qcow2
          virt-resize --expand /dev/sda1 original.qcow2 debian-12-xfs-uncompacted.qcow2
          guestfish --rw -a debian-12-xfs-uncompacted.qcow2 -i <<'EOF'
          fstransform / xfs force:true
          EOF
          echo "Filesystem conversion to XFS complete."

      - name: Sparsify Image to Reduce Physical Size
        env:
          LIBGUESTFS_BACKEND: direct
        run: |
          # 步骤 1: 在文件系统内部，将所有可用空间用零填充，然后删除零文件。
          # 'dd' 命令会因为“磁盘空间不足”而失败，这是预期行为，所以我们用 '|| true' 来忽略这个错误。
          guestfish --rw -a debian-12-xfs-uncompacted.qcow2 -i <<'EOF'
          sh "dd if=/dev/zero of=/zero.file bs=4M || true"
          rm /zero.file
          EOF
          echo "Free space zeroed out."
          
          # 步骤 2: 使用 qemu-img convert 进行转换。
          # 它会自动将零块转换成新 qcow2 文件中的“空洞”，从而实现压缩和瘦身。
          qemu-img convert -c -O qcow2 debian-12-xfs-uncompacted.qcow2 debian-12-xfs.qcow2
          
          echo "Image sparsified. Final physical size:"
          ls -lh debian-12-xfs.qcow2

      - name: Upload Compacted qcow2 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: debian-12-xfs-qcow2
          path: debian-12-xfs.qcow2
          retention-days: 7
