name: Build and Compact Debian XFS Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends qemu-utils libguestfs-tools xfsprogs libguestfs-xfs

      - name: Configure libguestfs for CI Environment
        run: |
          sudo mkdir -p /etc/libguestfs-tools.d
          echo 'apparmor_disable = 1' | sudo tee /etc/libguestfs-tools.d/99-apparmor-disable.conf

      - name: Download Debian Cloud Image
        run: |
          wget -O original.qcow2 https://cdimage.debian.org/images/cloud/bookworm/latest/debian-12-nocloud-amd64.qcow2

      - name: Resize, Convert, and Sparsify Image
        run: |
          set -ex

          qemu-img create -f qcow2 -o compression_type=zlib debian-12-xfs-uncompacted.qcow2 10G
          chmod 666 debian-12-xfs-uncompacted.qcow2
          
          # 步骤 1: 调整大小 (保持不变)
          sudo LIBGUESTFS_DEBUG=1 virt-resize --expand /dev/sda1 original.qcow2 debian-12-xfs-uncompacted.qcow2
          
          # 核心修正: 使用 virt-rescue 来执行 fstransform
          # virt-rescue 提供了 fstransform 所需的“未挂载”环境，从而解决了根本矛盾
          echo "Converting filesystem on /dev/sda3 to XFS using virt-rescue..."
          sudo LIBGUESTFS_DEBUG=1 virt-rescue --rw -a debian-12-xfs-uncompacted.qcow2 --sh "fstransform /dev/sda3 xfs"
          echo "Filesystem conversion to XFS complete."
          
          # 步骤 3: 使用 guestfish 进行零填充 (此工具非常适合此任务)
          echo "Zeroing out free space using guestfish..."
          sudo LIBGUESTFS_DEBUG=1 guestfish --rw -a debian-12-xfs-uncompacted.qcow2 <<'EOF'
          run
          mount /dev/sda3 /
          sh "dd if=/dev/zero of=/zero.file bs=4M status=progress || true"
          rm /zero.file
          umount /
          EOF
          echo "Free space zeroed out."
          
          sudo sync
          
          qemu-img convert -c -O qcow2 debian-12-xfs-uncompacted.qcow2 debian-12-xfs.qcow2
          
          echo "Image sparsified. Final physical size:"
          ls -lh debian-12-xfs.qcow2

      - name: Upload Compacted qcow2 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: debian-12-xfs-qcow2
          path: debian-12-xfs.qcow2
          retention-days: 7
