name: Build and Compact Debian XFS Image

on:
  push:
    branches:
      - main
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends qemu-utils libguestfs-tools

      - name: Download Debian Cloud Image
        run: |
          wget -O original.qcow2 https://cdimage.debian.org/images/cloud/bookworm/latest/debian-12-nocloud-amd64.qcow2

      - name: Convert Filesystem to XFS and Resize
        env:
          LIBGUESTFS_BACKEND: direct
        run: |
          # 1. 创建目标镜像
          qemu-img create -f qcow2 -o compression_type=zlib debian-12-xfs-uncompacted.qcow2 10G
          
          # 2. 修正权限问题
          chmod a+r debian-12-xfs-uncompacted.qcow2
          
          # 3. 复制并扩展分区
          virt-resize --expand /dev/sda1 original.qcow2 debian-12-xfs-uncompacted.qcow2
          
          # 4. 转换文件系统为 XFS
          #    修正：让 -i 选项自动挂载，然后直接对挂载点 '/' 进行转换
          guestfish --rw -a debian-12-xfs-uncompacted.qcow2 -i <<'EOF'
          fstransform / xfs
          EOF
          
          echo "Filesystem conversion to XFS complete."

      - name: Sparsify Image to Reduce Physical Size
        env:
          LIBGUESTFS_BACKEND: direct
        run: |
          virt-sparsify debian-12-xfs-uncompacted.qcow2 debian-12-xfs.qcow2
          
          echo "Image sparsified. Final physical size:"
          ls -lh debian-12-xfs.qcow2

      - name: Upload Compacted qcow2 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: debian-12-xfs-qcow2
          path: debian-12-xfs.qcow2
          retention-days: 7
