      - name: Resize, Convert, and Generate Final Images
        run: |
          set -ex
          
          BASENAME=${{ steps.image_info.outputs.basename }}
          UNCOMPACTED_IMAGE_NAME="${BASENAME}-uncompacted.qcow2"

          # 步骤 1: 创建目标镜像 (大小改为 3.5G) 并调整分区
          # 这提供了足够的空间来避免 virt-resize 错误
          qemu-img create -f qcow2 -o compression_type=zlib $UNCOMPACTED_IMAGE_NAME 3.5G
          chmod 666 $UNCOMPACTED_IMAGE_NAME
          sudo virt-resize --expand /dev/sda1 original.qcow2 $UNCOMPACTED_IMAGE_NAME
          
          # 步骤 2: 动态查找根分区
          echo "Finding the root partition to convert..."
          ROOT_PARTITION=$(sudo virt-filesystems --long --filesystems -a $UNCOMPACTED_IMAGE_NAME | grep -w 'ext4' | awk '{print $1}')
          
          if [ -z "$ROOT_PARTITION" ]; then
            echo "::error::Could not find the ext4 root partition to convert."
            exit 1
          fi
          echo "Root partition found: $ROOT_PARTITION"

          # 步骤 3: 转换文件系统为 XFS
          echo "Converting filesystem on $ROOT_PARTITION to XFS..."
          sudo virt-rescue --rw -a $UNCOMPACTED_IMAGE_NAME --sh "fstransform ${ROOT_PARTITION} xfs"
          
          # 步骤 4: 零填充自由空间以实现最大稀疏化
          echo "Zeroing out free space to enable maximum sparsification..."
          sudo guestfish --rw -a $UNCOMPACTED_IMAGE_NAME <<EOF
          run
          mount ${ROOT_PARTITION} /
          sh "dd if=/dev/zero of=/zero.file bs=4M status=progress || true"
          rm /zero.file
          umount /
          EOF
          
          sudo sync
          
          # 步骤 5: 从母版生成所有稀疏的最终镜像
          echo "Converting the master image to all target formats (sparsified)..."
          
          qemu-img convert -c -O qcow2 $UNCOMPACTED_IMAGE_NAME "${BASENAME}.qcow2"
          
          # 同样在此处将 -S 选项的逻辑大小更新为 3.5G
          qemu-img convert -S 3.5G -O raw $UNCOMPACTED_IMAGE_NAME "${BASENAME}.raw"
          
          qemu-img convert -O vpc $UNCOMPACTED_IMAGE_NAME "${BASENAME}.vhd"
          
          qemu-img convert -O vhdx $UNCOMPACTED_IMAGE_NAME "${BASENAME}.vhdx"
          
          echo "Sparsified images generated. Physical sizes:"
          ls -lh ${BASENAME}.*
          echo "Disk usage:"
          du -sh ${BASENAME}.*
          
          # 步骤 6: 创建所有镜像的 Zstandard 压缩版本
          echo "Compressing all generated images with Zstandard..."
          for file in ${BASENAME}.qcow2 ${BASENAME}.raw ${BASENAME}.vhd ${BASENAME}.vhdx; do
            echo "Compressing $file..."
            zstd -T0 "$file" -o "${file}.zst"
          done

          echo "All compressed archives created."
          ls -lh ${BASENAME}.*.zst
