name: Build and Release Debian 13 (Trixie) XFS Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    # 需要写入权限来创建 Release
    permissions:
      contents: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends qemu-utils libguestfs-tools xfsprogs libguestfs-xfs

      - name: Configure libguestfs for CI Environment
        run: |
          sudo mkdir -p /etc/libguestfs-tools.d
          echo 'apparmor_disable = 1' | sudo tee /etc/libguestfs-tools.d/99-apparmor-disable.conf

      - name: Download Debian 13 (Trixie) Cloud Image
        run: |
          wget -O original.qcow2 https://cdimage.debian.org/images/cloud/trixie/daily/latest/debian-13-nocloud-amd64-daily.qcow2

      - name: Define Image Filename
        id: image_info
        run: echo "filename=debian-13-xfs.qcow2" >> $GITHUB_OUTPUT

      - name: Resize, Convert, and Sparsify Image
        run: |
          set -ex
          
          # 从上一步获取文件名
          IMAGE_NAME=${{ steps.image_info.outputs.filename }}
          UNCOMPACTED_IMAGE_NAME="debian-13-xfs-uncompacted.qcow2"

          qemu-img create -f qcow2 -o compression_type=zlib $UNCOMPACTED_IMAGE_NAME 10G
          chmod 666 $UNCOMPACTED_IMAGE_NAME
          
          sudo virt-resize --expand /dev/sda1 original.qcow2 $UNCOMPACTED_IMAGE_NAME
          
          echo "Converting filesystem on /dev/sda1 to XFS using virt-rescue..."
          sudo virt-rescue --rw -a $UNCOMPACTED_IMAGE_NAME --sh "fstransform /dev/sda1 xfs"
          echo "Filesystem conversion to XFS complete."
          
          echo "Zeroing out free space using guestfish..."
          sudo guestfish --rw -a $UNCOMPACTED_IMAGE_NAME <<'EOF'
          run
          mount /dev/sda1 /
          sh "dd if=/dev/zero of=/zero.file bs=4M status=progress || true"
          rm /zero.file
          umount /
          EOF
          echo "Free space zeroed out."
          
          sudo sync
          
          qemu-img convert -c -O qcow2 $UNCOMPACTED_IMAGE_NAME $IMAGE_NAME
          
          echo "Image sparsified. Final physical size:"
          ls -lh $IMAGE_NAME

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          # 要上传的文件
          files: ${{ steps.image_info.outputs.filename }}
          # 使用日期和时间生成一个唯一的 tag 和 Release 名称
          tag_name: debian-13-xfs-${{ GITHUB.RUN_ID }}
          name: "Debian 13 XFS Image Build ${{ GITHUB.RUN_ID }}"
          # 标记这是一个预发布版本
          prerelease: true

