name: Build and Compact Debian XFS Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends qemu-utils libguestfs-tools xfsprogs linux-headers-generic libguestfs-xfs

      - name: Download Debian Cloud Image
        run: |
          wget -O original.qcow2 https://cdimage.debian.org/images/cloud/bookworm/latest/debian-12-nocloud-amd64.qcow2

      # 核心修正：将所有 libguestfs 操作放在一个步骤中，并设置环境变量
      - name: Resize, Convert, and Sparsify Image
        env:
          # 这个环境变量对所有下面的 sudo 命令都至关重要
          LIBGUESTFS_BACKEND: direct
        run: |
          set -ex

          # 创建和准备镜像
          qemu-img create -f qcow2 -o compression_type=zlib debian-12-xfs-uncompacted.qcow2 10G
          chmod 666 debian-12-xfs-uncompacted.qcow2
          
          # 此命令现在会继承 LIBGUESTFS_BACKEND
          sudo virt-resize --expand /dev/sda1 original.qcow2 debian-12-xfs-uncompacted.qcow2
          
          # 此命令现在也会继承 LIBGUESTFS_BACKEND，从而能正确初始化
          sudo guestfish --rw -a debian-12-xfs-uncompacted.qcow2 -x 'fstransform / xfs force:true'
          echo "Filesystem conversion to XFS complete."
          
          # 此命令同样继承 LIBGUESTFS_BACKEND
          sudo guestfish --rw -a debian-12-xfs-uncompacted.qcow2 \
            -x 'sh "dd if=/dev/zero of=/zero.file bs=4M || true"' \
            -x 'rm /zero.file'
          echo "Free space zeroed out."
          
          # 同步文件系统缓存
          sudo sync
          
          # 最后的压缩步骤
          qemu-img convert -c -O qcow2 debian-12-xfs-uncompacted.qcow2 debian-12-xfs.qcow2
          
          echo "Image sparsified. Final physical size:"
          ls -lh debian-12-xfs.qcow2

      - name: Upload Compacted qcow2 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: debian-12-xfs-qcow2
          path: debian-12-xfs.qcow2
          retention-days: 7
